package lisakom.com.enumerations;

public enum Genre {
    PROGRAMMING_BASICS,
    ENGLISH_LANGUAGE,
    ALGORITHMS_AND_DATA_STRUCTURES,
    VERSION_CONTRLS_SYSTEMS,
    UNIX_LINUX,
    PYTHON,
    RUBY,
    ODP,
    PATTERNS,
    ASSEMBLER,
    C,
    CPLUSPLUS,
    CSHARP,
    JAVA,
    HTML_HTML5_CSS,
    REGULAR_EXPRESSIONS,
    PHP,
    MYSQL,
    JAVASCRIPT,
    DATA_ANALYSIS,
    COMPUTER_NETWORK_SECURITY,
    MOBILE_DEVELOPMENT,
    QA_AUTOMATION


}
